# Generated by Django 4.1 on 2022-08-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("price", models.IntegerField(max_length=12)),
                ("quantity", models.IntegerField(max_length=12)),
                ("image", models.ImageField(upload_to="images/")),
                ("category", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
